---
title: "XXXXXX"
author: 
  - Benedict Cummins-Mburu
thanks: "Code and data are available at: [https://github.com/bennypk1/starter_folder](https://github.com/bennypk1/starter_folder)."
date: today
date-format: long
abstract: "XXX "
format: pdf
number-sections: true
bibliography: references.bib
---

```{r}
#| include: false
#| warning: false
#| message: false

library(tidyverse)
```


# Introduction

Urban landscapes are often warmer, on average, than their surrounding rural counterparts. This phenomenon (known as the Urban Heat Island Effect, and herafter referred to as the UHI) is largely driven by the lack of vegetated surfaces (Yang et al., 2016). The primary surface materials in urban landscapes (e.g. concrete, tar, ashphalt and gravel) absorb more solar radiation (albedos typically ranging from 0.1 to 0.2) than more natural landscapes with very little anthropogenic activity (albedos typically ranging from 0.7 to 0.85) Owing to the UHI among other factors, climate-change-induced global warming is projected to disproportionately affect urban centers (CITATION) ; citites have predicted temerature increases of X degrees C, an X degree increase from the global average (CITATION). [need to talk about why heating matters or no?].

Faced with these unique risks, many municipalities around the world (e.g. Basel, Switzerland and Berlin, Germany) have adoped green roof by-laws (hereafter referred to as GRBLs) to mitigate against the UHI. Green roofs are defined by Berardi et al. (2014) as "roofs with plants in their final layer", and offer many building and/or city-level services including stormwater management and increased public access to nearby green spaces (Berardi et al.,  2014). Most obviously, green roofs decrease the overall solar absorbance of a municipality by increasing the vegetated area, theoretically reducing the UHI.

Toronto is the first city in North America to have had a By-law requiring the construction of green roofs (City of Toronto, 2026). From January 2010 to November 2025, all new developments and extensions with a floor area in excess of 2000 m2  were required to construct a green roof, defined by the City as “an extension of [a roof], built on top of a human-made structure, that allows vegetation to grow in a growing medium” (City of Toronto, 2026). Complimenting their GRBL, the City also implemented an Eco-Roof Incentive Program (ERIP) to support the voluntary installation of green roofs on homes and buildings (City of Toronto, 2026). 

In this report, Recent research has found that, while overall area is the most important factor in determining a green roofs's ability to offset the UHI, the relative spatial arrangement of green spaces in a city matters as well, where cities with (Berardi et al., 2014). In this report, we sought to assess whether or not Toronto's GRBL was effective in homogenizing the distribution of vegetated area in the city, effectively optimizing the city's UHI offset. We leveraged data from Open Data Toronto to (1) document the spatial distribution of current ground-level "green spaces" (e.g. parks, etc.), and (2) document the spatial distribution of green roofs, and (3) analyze whether or not green roofs "fill the gaps" missed on the surface. We hypothesize that increased rates of development in downtown areas (and therefore higher absolute green roof numbers) would lead to

[Findings]

The following report is structutred as follows. Section 2 provides an overview of the datasets used, as well as summaries of vasriables relevant for analysis. Section 3 details our findings [and will primarily consist of comparative maps], Section 4 discussion and limitations.

# Data {#sec-data}

## Overview

The dataset used in this report represents an up-to-date collection of 1235 building permits related to Toronto’s GRBL (n=1194) and ERIP (n=41). Both the GRBL and ERIP were adopted in 2009 by the Toronto City Council, and entered into effect on January 31, 2010. The GRBL was officially repealed in November 2025, making green roofs voluntary for private developers (City of Toronto, 2026). Permit information (described in more detail below) of all structures for which the GRBL or ERIP has applied are made public and updated weekly on the City’s Open Data website (City of Toronto, 2026), accessed for this report on May 6, 2026. The raw dataset also contained an additional 15 definitively cancelled projects, which were removed [in one sentence, why].

Each permit is assigned a Permit Number, which consists of the last two digits of its application year (e.g. 11 for 2011), followed by a 6-digit IBMS-generated sequence. After issuance, permit applications may be revised, the proposed changes of which may qualify for GRBL or ERIP. Such revisions are recorded using the same Permit Number, and distinguished from the original permit application by an integer value (called the Recording Number). Therefore, identifying truly unique green roofs requires specifying both a Permit and Revision Number (this one-to-one mapping was violated once in the dataset ; the structure’s duplicate observations were removed and assumed to be errors). Permit-revision pairs are each assigned types (e.g. “New Building”, “Small Residential Projects”), a current status (e.g. “Closed”, “Revision Issued”), and a written description of the proposed project. Dates of permit application, issuance, and completion are also provided where applicable.  In addition, the full address, forward sortation area (FSA ; i.e. the first three digits of the postal code), type (e.g. “University”, “SFD – Detached”), and green roof size (in m2) of the associated structure is provided.
All data acquisition, cleaning, tabulation, and visualization tasks were conducted within the R Statistical Software (R Core Team, 2023). Notable packages used in this report include `opendatatoronto` (Gelfand, 2022),`tidyverse` (Wickham et al., 2019), and `canadianmaps` (Cayen, 2024). 

## Outcome variables

Add graphs, tables and text. Use sub-sub-headings for each outcome variable or update the subheading to be singular.

Talk more about it.

And also planes (@fig-planes). (You can change the height and width, but don't worry about doing that until you have finished every other aspect of the paper - Quarto will try to make it look nice and the defaults usually work well once you have enough text.)

Talk way more about it. 

## Predictor variables

Add graphs, tables and text.

Use sub-sub-headings for each outcome variable and feel free to combine a few into one if they go together naturally.


# Results

Our results are summarized in @tbl-modelresults.


# Discussion

## First discussion point {#sec-first-point}

If my paper were 10 pages, then should be be at least 2.5 pages. The discussion is a chance to show off what you know and what you learnt from all this. 

## Second discussion point

Please don't use these as sub-heading labels - change them to be what your point actually is.

## Third discussion point

## Weaknesses and next steps

Weaknesses and next steps should also be included.

\newpage

\appendix

# Appendix {-}


# Additional data details

## Posterior predictive check

In @fig-ppcheckandposteriorvsprior-1 we implement a posterior predictive check. This shows...

In @fig-ppcheckandposteriorvsprior-2 we compare the posterior with the prior. This shows... 


## Diagnostics

@fig-stanareyouokay-1 is a trace plot. It shows... This suggests...

@fig-stanareyouokay-2 is a Rhat plot. It shows... This suggests...




\newpage


# References


